steps:
  # Gateway
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-east4-docker.pkg.dev/study-microservice-nestjs/gateway/develoment",
        "-f",
        "./Dockerfile",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-east4-docker.pkg.dev/study-microservice-nestjs/gateway/develoment",
      ]
