export enum ExceptionErrorMessageEnum {
  /**
   * Access Control Mongodb Errors
   */
  GATEWAY_MANAGER_ACCESS_CONTROL_NOT_NULL_OR_UNDEFINED_DTO_ERROR_0001 = 'GATEWAY_MANAGER_ACCESS_CONTROL_NOT_NULL_OR_UNDEFINED_DTO_ERROR_0001',
  GATEWAY_MANAGER_ACCESS_CONTROL_IS_BOOLEAN_DTO_ERROR_0002 = 'GATEWAY_MANAGER_ACCESS_CONTROL_NOT_NULL_OR_UNDEFINED_DTO_ERROR_0002',

  GATEWAY_MANAGER_ACCESS_CONTROL_ABSTRACT_STATUS_DTO_ERROR_0001 = 'GATEWAY_MANAGER_ACCESS_CONTROL_ABSTRACT_STATUS_DTO_ERROR_0001',
  GATEWAY_MANAGER_ACCESS_CONTROL_ABSTRACT_STATUS_DTO_ERROR_0002 = 'GATEWAY_MANAGER_ACCESS_CONTROL_ABSTRACT_STATUS_DTO_ERROR_0002',
  GATEWAY_MANAGER_ACCESS_CONTROL_ABSTRACT_STATUS_DTO_ERROR_0003 = 'GATEWAY_MANAGER_ACCESS_CONTROL_ABSTRACT_STATUS_DTO_ERROR_0003',

  /**
   * Access Control Auth Errors
   */
  GATEWAY_MANAGER_ACCESS_CONTROL_AUTH_DTO_ERROR_0001 = 'GATEWAY_MANAGER_ACCESS_CONTROL_AUTH_DTO_ERROR_0001',
  GATEWAY_MANAGER_ACCESS_CONTROL_AUTH_DTO_ERROR_0002 = 'GATEWAY_MANAGER_ACCESS_CONTROL_AUTH_DTO_ERROR_0002',
  GATEWAY_MANAGER_ACCESS_CONTROL_AUTH_DTO_ERROR_0003 = 'GATEWAY_MANAGER_ACCESS_CONTROL_AUTH_DTO_ERROR_0003',
  GATEWAY_MANAGER_ACCESS_CONTROL_AUTH_DTO_ERROR_0004 = 'GATEWAY_MANAGER_ACCESS_CONTROL_AUTH_DTO_ERROR_0004',

  /**
   * Access Control Auth Errors
   */
  GATEWAY_MANAGER_ACCESS_CONTROL_AUTH_CONFIRM_SIG_UP_DTO_ERROR_0001 = 'GATEWAY_MANAGER_ACCESS_CONTROL_AUTH_CONFIRM_SIG_UP_DTO_ERROR_0001',
  GATEWAY_MANAGER_ACCESS_CONTROL_AUTH_CONFIRM_SIG_UP_DTO_ERROR_0002 = 'GATEWAY_MANAGER_ACCESS_CONTROL_AUTH_CONFIRM_SIG_UP_DTO_ERROR_0002',
  GATEWAY_MANAGER_ACCESS_CONTROL_AUTH_CONFIRM_SIG_UP_DTO_ERROR_0003 = 'GATEWAY_MANAGER_ACCESS_CONTROL_AUTH_CONFIRM_SIG_UP_DTO_ERROR_0003',
  GATEWAY_MANAGER_ACCESS_CONTROL_AUTH_CONFIRM_SIG_UP_DTO_ERROR_0004 = 'GATEWAY_MANAGER_ACCESS_CONTROL_AUTH_CONFIRM_SIG_UP_DTO_ERROR_0004',
  GATEWAY_MANAGER_ACCESS_CONTROL_AUTH_CONFIRM_SIG_UP_DTO_ERROR_0005 = 'GATEWAY_MANAGER_ACCESS_CONTROL_AUTH_CONFIRM_SIG_UP_DTO_ERROR_0005',
  GATEWAY_MANAGER_ACCESS_CONTROL_AUTH_CONFIRM_SIG_UP_DTO_ERROR_0006 = 'GATEWAY_MANAGER_ACCESS_CONTROL_AUTH_CONFIRM_SIG_UP_DTO_ERROR_0006',
  GATEWAY_MANAGER_ACCESS_CONTROL_AUTH_CONFIRM_SIG_UP_DTO_ERROR_0007 = 'GATEWAY_MANAGER_ACCESS_CONTROL_AUTH_CONFIRM_SIG_UP_DTO_ERROR_0007',

  /**
   * Access Control Auth Resend Code Errors
   */
  GATEWAY_MANAGER_ACCESS_CONTROL_AUTH_RESEND_CODE_DTO_ERROR_0001 = 'GATEWAY_MANAGER_ACCESS_CONTROL_AUTH_RESEND_CODE_DTO_ERROR_0001',
  GATEWAY_MANAGER_ACCESS_CONTROL_AUTH_RESEND_CODE_DTO_ERROR_0002 = 'GATEWAY_MANAGER_ACCESS_CONTROL_AUTH_RESEND_CODE_DTO_ERROR_0002',

  /**
   * Access Control Role Created Errors
   */
  GATEWAY_MANAGER_ACCESS_CONTROL_ROLE_DTO_CREATED_ERROR_0001 = 'GATEWAY_MANAGER_ACCESS_CONTROL_ROLE_DTO_CREATED_ERROR_0001',
  GATEWAY_MANAGER_ACCESS_CONTROL_ROLE_DTO_CREATED_ERROR_0002 = 'GATEWAY_MANAGER_ACCESS_CONTROL_ROLE_DTO_CREATED_ERROR_0002',
  GATEWAY_MANAGER_ACCESS_CONTROL_ROLE_DTO_CREATED_ERROR_0003 = 'GATEWAY_MANAGER_ACCESS_CONTROL_ROLE_DTO_CREATED_ERROR_0003',
  GATEWAY_MANAGER_ACCESS_CONTROL_ROLE_DTO_CREATED_ERROR_0004 = 'GATEWAY_MANAGER_ACCESS_CONTROL_ROLE_DTO_CREATED_ERROR_0004',
  GATEWAY_MANAGER_ACCESS_CONTROL_ROLE_DTO_CREATED_ERROR_0005 = 'GATEWAY_MANAGER_ACCESS_CONTROL_ROLE_DTO_CREATED_ERROR_0005',
  GATEWAY_MANAGER_ACCESS_CONTROL_ROLE_DTO_CREATED_ERROR_0006 = 'GATEWAY_MANAGER_ACCESS_CONTROL_ROLE_DTO_CREATED_ERROR_0006',
  GATEWAY_MANAGER_ACCESS_CONTROL_ROLE_DTO_CREATED_ERROR_0007 = 'GATEWAY_MANAGER_ACCESS_CONTROL_ROLE_DTO_CREATED_ERROR_0007',
  GATEWAY_MANAGER_ACCESS_CONTROL_ROLE_DTO_CREATED_ERROR_0008 = 'GATEWAY_MANAGER_ACCESS_CONTROL_ROLE_DTO_CREATED_ERROR_0008',

  /**
   * Access Control Role Find One Errors
   */
  GATEWAY_MANAGER_ACCESS_CONTROL_ROLE_DTO_FIND_ONE_ERROR_0001 = 'GATEWAY_MANAGER_ACCESS_CONTROL_ROLE_DTO_FIND_ONE_ERROR_0001',
  GATEWAY_MANAGER_ACCESS_CONTROL_ROLE_DTO_FIND_ONE_ERROR_0002 = 'GATEWAY_MANAGER_ACCESS_CONTROL_ROLE_DTO_FIND_ONE_ERROR_0002',
  GATEWAY_MANAGER_ACCESS_CONTROL_ROLE_DTO_FIND_ONE_ERROR_0003 = 'GATEWAY_MANAGER_ACCESS_CONTROL_ROLE_DTO_FIND_ONE_ERROR_0003',
  GATEWAY_MANAGER_ACCESS_CONTROL_ROLE_DTO_FIND_ONE_ERROR_0004 = 'GATEWAY_MANAGER_ACCESS_CONTROL_ROLE_DTO_FIND_ONE_ERROR_0004',

  /**
   * Access Control Role Find Id Errors
   */
  GATEWAY_MANAGER_ACCESS_CONTROL_ROLE_DTO_FIND_ID_ERROR_0001 = 'GATEWAY_MANAGER_ACCESS_CONTROL_ROLE_DTO_FIND_ID_ERROR_0001',
  GATEWAY_MANAGER_ACCESS_CONTROL_ROLE_DTO_FIND_ID_ERROR_0002 = 'GATEWAY_MANAGER_ACCESS_CONTROL_ROLE_DTO_FIND_ID_ERROR_0002',
  GATEWAY_MANAGER_ACCESS_CONTROL_ROLE_DTO_FIND_ID_ERROR_0003 = 'GATEWAY_MANAGER_ACCESS_CONTROL_ROLE_DTO_FIND_ID_ERROR_0003',
  GATEWAY_MANAGER_ACCESS_CONTROL_ROLE_DTO_FIND_ID_ERROR_0004 = 'GATEWAY_MANAGER_ACCESS_CONTROL_ROLE_DTO_FIND_ID_ERROR_0004',

  /**
   * Access Control Permission Created Errors
   */
  GATEWAY_MANAGER_ACCESS_CONTROL_PERMISSION_DTO_CREATED_ERROR_0001 = 'GATEWAY_MANAGER_ACCESS_CONTROL_PERMISSION_DTO_CREATED_ERROR_0001',
  GATEWAY_MANAGER_ACCESS_CONTROL_PERMISSION_DTO_CREATED_ERROR_0002 = 'GATEWAY_MANAGER_ACCESS_CONTROL_PERMISSION_DTO_CREATED_ERROR_0002',
  GATEWAY_MANAGER_ACCESS_CONTROL_PERMISSION_DTO_CREATED_ERROR_0003 = 'GATEWAY_MANAGER_ACCESS_CONTROL_PERMISSION_DTO_CREATED_ERROR_0003',
  GATEWAY_MANAGER_ACCESS_CONTROL_PERMISSION_DTO_CREATED_ERROR_0004 = 'GATEWAY_MANAGER_ACCESS_CONTROL_PERMISSION_DTO_CREATED_ERROR_0004',
  GATEWAY_MANAGER_ACCESS_CONTROL_PERMISSION_DTO_CREATED_ERROR_0005 = 'GATEWAY_MANAGER_ACCESS_CONTROL_PERMISSION_DTO_CREATED_ERROR_0005',
  GATEWAY_MANAGER_ACCESS_CONTROL_PERMISSION_DTO_CREATED_ERROR_0006 = 'GATEWAY_MANAGER_ACCESS_CONTROL_PERMISSION_DTO_CREATED_ERROR_0006',
  GATEWAY_MANAGER_ACCESS_CONTROL_PERMISSION_DTO_CREATED_ERROR_0007 = 'GATEWAY_MANAGER_ACCESS_CONTROL_PERMISSION_DTO_CREATED_ERROR_0007',
  GATEWAY_MANAGER_ACCESS_CONTROL_PERMISSION_DTO_CREATED_ERROR_0008 = 'GATEWAY_MANAGER_ACCESS_CONTROL_PERMISSION_DTO_CREATED_ERROR_0008',

  /**
   * Access Control Permission Find One Errors
   */
  GATEWAY_MANAGER_ACCESS_CONTROL_PERMISSION_DTO_FIND_ONE_ERROR_0001 = 'GATEWAY_MANAGER_ACCESS_CONTROL_PERMISSION_DTO_FIND_ONE_ERROR_0001',
  GATEWAY_MANAGER_ACCESS_CONTROL_PERMISSION_DTO_FIND_ONE_ERROR_0002 = 'GATEWAY_MANAGER_ACCESS_CONTROL_PERMISSION_DTO_FIND_ONE_ERROR_0002',
  GATEWAY_MANAGER_ACCESS_CONTROL_PERMISSION_DTO_FIND_ONE_ERROR_0003 = 'GATEWAY_MANAGER_ACCESS_CONTROL_PERMISSION_DTO_FIND_ONE_ERROR_0003',
  GATEWAY_MANAGER_ACCESS_CONTROL_PERMISSION_DTO_FIND_ONE_ERROR_0004 = 'GATEWAY_MANAGER_ACCESS_CONTROL_PERMISSION_DTO_FIND_ONE_ERROR_0004',

  /**
   * Access Control Permission Find Id Errors
   */
  GATEWAY_MANAGER_ACCESS_CONTROL_PERMISSION_DTO_FIND_ID_ERROR_0001 = 'GATEWAY_MANAGER_ACCESS_CONTROL_PERMISSION_DTO_FIND_ID_ERROR_0001',
  GATEWAY_MANAGER_ACCESS_CONTROL_PERMISSION_DTO_FIND_ID_ERROR_0002 = 'GATEWAY_MANAGER_ACCESS_CONTROL_PERMISSION_DTO_FIND_ID_ERROR_0002',
  GATEWAY_MANAGER_ACCESS_CONTROL_PERMISSION_DTO_FIND_ID_ERROR_0003 = 'GATEWAY_MANAGER_ACCESS_CONTROL_PERMISSION_DTO_FIND_ID_ERROR_0003',
  GATEWAY_MANAGER_ACCESS_CONTROL_PERMISSION_DTO_FIND_ID_ERROR_0004 = 'GATEWAY_MANAGER_ACCESS_CONTROL_PERMISSION_DTO_FIND_ID_ERROR_0004',

  /**
   * Access Control User Created Errors
   */
  GATEWAY_MANAGER_ACCESS_CONTROL_USER_DTO_CREATED_ERROR_0001 = 'GATEWAY_MANAGER_ACCESS_CONTROL_USER_DTO_CREATED_ERROR_0001',
  GATEWAY_MANAGER_ACCESS_CONTROL_USER_DTO_CREATED_ERROR_0002 = 'GATEWAY_MANAGER_ACCESS_CONTROL_USER_DTO_CREATED_ERROR_0002',
  GATEWAY_MANAGER_ACCESS_CONTROL_USER_DTO_CREATED_ERROR_0003 = 'GATEWAY_MANAGER_ACCESS_CONTROL_USER_DTO_CREATED_ERROR_0003',
  GATEWAY_MANAGER_ACCESS_CONTROL_USER_DTO_CREATED_ERROR_0004 = 'GATEWAY_MANAGER_ACCESS_CONTROL_USER_DTO_CREATED_ERROR_0004',
  GATEWAY_MANAGER_ACCESS_CONTROL_USER_DTO_CREATED_ERROR_0005 = 'GATEWAY_MANAGER_ACCESS_CONTROL_USER_DTO_CREATED_ERROR_0005',
  GATEWAY_MANAGER_ACCESS_CONTROL_USER_DTO_CREATED_ERROR_0006 = 'GATEWAY_MANAGER_ACCESS_CONTROL_USER_DTO_CREATED_ERROR_0006',
  GATEWAY_MANAGER_ACCESS_CONTROL_USER_DTO_CREATED_ERROR_0007 = 'GATEWAY_MANAGER_ACCESS_CONTROL_USER_DTO_CREATED_ERROR_0007',
  GATEWAY_MANAGER_ACCESS_CONTROL_USER_DTO_CREATED_ERROR_0008 = 'GATEWAY_MANAGER_ACCESS_CONTROL_USER_DTO_CREATED_ERROR_0008',
  GATEWAY_MANAGER_ACCESS_CONTROL_USER_DTO_CREATED_ERROR_0009 = 'GATEWAY_MANAGER_ACCESS_CONTROL_USER_DTO_CREATED_ERROR_0009',
  GATEWAY_MANAGER_ACCESS_CONTROL_USER_DTO_CREATED_ERROR_0010 = 'GATEWAY_MANAGER_ACCESS_CONTROL_USER_DTO_CREATED_ERROR_0010',
  GATEWAY_MANAGER_ACCESS_CONTROL_USER_DTO_CREATED_ERROR_0011 = 'GATEWAY_MANAGER_ACCESS_CONTROL_USER_DTO_CREATED_ERROR_0011',

  /**
   * Access Control User Find One Errors
   */
  GATEWAY_MANAGER_ACCESS_CONTROL_USER_DTO_FIND_ONE_ERROR_0001 = 'GATEWAY_MANAGER_ACCESS_CONTROL_USER_DTO_FIND_ONE_ERROR_0001',
  GATEWAY_MANAGER_ACCESS_CONTROL_USER_DTO_FIND_ONE_ERROR_0002 = 'GATEWAY_MANAGER_ACCESS_CONTROL_USER_DTO_FIND_ONE_ERROR_0002',
  GATEWAY_MANAGER_ACCESS_CONTROL_USER_DTO_FIND_ONE_ERROR_0003 = 'GATEWAY_MANAGER_ACCESS_CONTROL_USER_DTO_FIND_ONE_ERROR_0003',
  GATEWAY_MANAGER_ACCESS_CONTROL_USER_DTO_FIND_ONE_ERROR_0004 = 'GATEWAY_MANAGER_ACCESS_CONTROL_USER_DTO_FIND_ONE_ERROR_0004',

  /**
   * Access Control User Find Id Errors
   */
  GATEWAY_MANAGER_ACCESS_CONTROL_USER_DTO_FIND_ID_ERROR_0001 = 'GATEWAY_MANAGER_ACCESS_CONTROL_USER_DTO_FIND_ID_ERROR_0001',
  GATEWAY_MANAGER_ACCESS_CONTROL_USER_DTO_FIND_ID_ERROR_0002 = 'GATEWAY_MANAGER_ACCESS_CONTROL_USER_DTO_FIND_ID_ERROR_0002',
  GATEWAY_MANAGER_ACCESS_CONTROL_USER_DTO_FIND_ID_ERROR_0003 = 'GATEWAY_MANAGER_ACCESS_CONTROL_USER_DTO_FIND_ID_ERROR_0003',
  GATEWAY_MANAGER_ACCESS_CONTROL_USER_DTO_FIND_ID_ERROR_0004 = 'GATEWAY_MANAGER_ACCESS_CONTROL_USER_DTO_FIND_ID_ERROR_0004',

  /**
   * Access Control Mongodb Errors
   */
  MICRO_MANAGER_MONGO_DB_ERROR_0001 = 'MICRO_MANAGER_MONGO_DB_ERROR_0001', //'Invalid user credentials.',
  MICRO_MANAGER_MONGO_DB_ERROR_0002 = 'MICRO_MANAGER_MONGO_DB_ERROR_0002', //'Invalid user credentials.',
  MICRO_MANAGER_MONGO_DB_ERROR_0003 = 'MICRO_MANAGER_MONGO_DB_ERROR_0003', //'Invalid user credentials.',
  MICRO_MANAGER_MONGO_DB_ERROR_0004 = 'MICRO_MANAGER_MONGO_DB_ERROR_0004', //'Invalid user credentials.',
  MICRO_MANAGER_MONGO_DB_ERROR_0005 = 'MICRO_MANAGER_MONGO_DB_ERROR_0005', //'Invalid user credentials
  MICRO_MANAGER_MONGO_DB_ERROR_0006 = 'MICRO_MANAGER_MONGO_DB_ERROR_0006', //'Invalid user credentials.',
  MICRO_MANAGER_MONGO_DB_ERROR_0007 = 'MICRO_MANAGER_MONGO_DB_ERROR_0007', //'Invalid user credentials.',
  MICRO_MANAGER_MONGO_DB_ERROR_0008 = 'MICRO_MANAGER_MONGO_DB_ERROR_0008', //'Invalid user credentials.',
  MICRO_MANAGER_MONGO_DB_ERROR_0009 = 'MICRO_MANAGER_MONGO_DB_ERROR_0009', //'Invalid user credentials.',
  MICRO_MANAGER_MONGO_DB_ERROR_0010 = 'MICRO_MANAGER_MONGO_DB_ERROR_0010', //'Invalid user credentials.',
  MICRO_MANAGER_MONGO_DB_ERROR_0011 = 'MICRO_MANAGER_MONGO_DB_ERROR_0011', //'Invalid user credentials.',
  MICRO_MANAGER_MONGO_DB_ERROR_0012 = 'MICRO_MANAGER_MONGO_DB_ERROR_0012', //'Invalid user credentials.',

  /**
   * Cognito Errors
   */
  COGNITO_AUTH_ERROR_0000 = 'COGNITO_AUTH_ERROR_0000',
  COGNITO_AUTH_ERROR_0001 = 'COGNITO_AUTH_ERROR_0001',
  COGNITO_AUTH_ERROR_0002 = 'COGNITO_AUTH_ERROR_0002',
  COGNITO_AUTH_ERROR_0003 = 'COGNITO_AUTH_ERROR_0003',
  COGNITO_AUTH_ERROR_0004 = 'COGNITO_AUTH_ERROR_0004',
  COGNITO_AUTH_ERROR_0005 = 'COGNITO_AUTH_ERROR_0005',
  COGNITO_AUTH_ERROR_0006 = 'COGNITO_AUTH_ERROR_0006',
  COGNITO_AUTH_ERROR_0007 = 'COGNITO_AUTH_ERROR_0007',
  COGNITO_AUTH_ERROR_0008 = 'COGNITO_AUTH_ERROR_0008',
  COGNITO_AUTH_ERROR_0009 = 'COGNITO_AUTH_ERROR_0009',
  COGNITO_AUTH_ERROR_0010 = 'COGNITO_AUTH_ERROR_0010',
  COGNITO_AUTH_ERROR_0011 = 'COGNITO_AUTH_ERROR_0011',
  COGNITO_AUTH_ERROR_0012 = 'COGNITO_AUTH_ERROR_0012',
  COGNITO_AUTH_ERROR_0013 = 'COGNITO_AUTH_ERROR_0013',

  /**
   * User Errors
   */
  MICRO_MANAGER_USER_ERROR_0000 = 'MICRO_MANAGER_USER_ERROR_0000', //'Invalid request payload.',
  MICRO_MANAGER_USER_ERROR_0001 = 'MICRO_MANAGER_USER_ERROR_0001', //'Invalid request payload.',
  MICRO_MANAGER_USER_ERROR_0002 = 'MICRO_MANAGER_USER_ERROR_0002', //'Authentication failed.',
  MICRO_MANAGER_USER_ERROR_0003 = 'MICRO_MANAGER_USER_ERROR_0003', //'User does not exist.',
  MICRO_MANAGER_USER_ERROR_0004 = 'MICRO_MANAGER_USER_ERROR_0004', //'Invalid user credentials.',
  MICRO_MANAGER_USER_ERROR_0005 = 'MICRO_MANAGER_USER_ERROR_0005', //'Invalid user credentials.',
  MICRO_MANAGER_USER_ERROR_0006 = 'MICRO_MANAGER_USER_ERROR_0006', //'Invalid user credentials.',

  /**
   * Access Control Role Errors
   */
  MICRO_MANAGER_ACCESS_CONTROL_ERROR_0000 = 'MICRO_MANAGER_ACCESS_CONTROL_ERROR_0000', //'Invalid request payload.',
  MICRO_MANAGER_ACCESS_CONTROL_ROLE_ERROR_0001 = 'MICRO_MANAGER_ACCESS_CONTROL_ROLE_ERROR_0001', //'Invalid request payload.',
  MICRO_MANAGER_ACCESS_CONTROL_ROLE_ERROR_0002 = 'MICRO_MANAGER_ACCESS_CONTROL_ROLE_ERROR_0002', //'Authentication failed.',
  MICRO_MANAGER_ACCESS_CONTROL_ROLE_ERROR_0003 = 'MICRO_MANAGER_ACCESS_CONTROL_ROLE_ERROR_0003', //'User does not exist.',
  MICRO_MANAGER_ACCESS_CONTROL_ROLE_ERROR_0004 = 'MICRO_MANAGER_ACCESS_CONTROL_ROLE_ERROR_0004', //'Invalid user credentials.',
  MICRO_MANAGER_ACCESS_CONTROL_ROLE_ERROR_0005 = 'MICRO_MANAGER_ACCESS_CONTROL_ROLE_ERROR_0005', //'Invalid user credentials.',
  MICRO_MANAGER_ACCESS_CONTROL_ROLE_ERROR_0006 = 'MICRO_MANAGER_ACCESS_CONTROL_ROLE_ERROR_0006', //'Invalid user credentials.',

  /**
   * Access Control Permission Errors
   */
  MICRO_MANAGER_ACCESS_CONTROL_PERMISSION_ERROR_0007 = 'MICRO_MANAGER_ACCESS_CONTROL_PERMISSION_ERROR_0007', //'Invalid user credentials.',
  MICRO_MANAGER_ACCESS_CONTROL_PERMISSION_ERROR_0008 = 'MICRO_MANAGER_ACCESS_CONTROL_PERMISSION_ERROR_0008', //'Invalid user credentials.',
  MICRO_MANAGER_ACCESS_CONTROL_PERMISSION_ERROR_0009 = 'MICRO_MANAGER_ACCESS_CONTROL_PERMISSION_ERROR_0009', //'Invalid user credentials.',
  MICRO_MANAGER_ACCESS_CONTROL_PERMISSION_ERROR_0010 = 'MICRO_MANAGER_ACCESS_CONTROL_PERMISSION_ERROR_0010', //'Invalid user credentials.',
  MICRO_MANAGER_ACCESS_CONTROL_PERMISSION_ERROR_0011 = 'MICRO_MANAGER_ACCESS_CONTROL_PERMISSION_ERROR_0011', //'Invalid user credentials
  MICRO_MANAGER_ACCESS_CONTROL_PERMISSION_ERROR_0012 = 'MICRO_MANAGER_ACCESS_CONTROL_PERMISSION_ERROR_0012', //'Invalid user credentials.',
}
