export enum ExceptionErrorMessageEnum {
  GATEWAY_VALIDATOR_DTO_IS_BOOLEAN_ERROR_0001 = 'GATEWAY_VALIDATOR_DTO_IS_BOOLEAN_ERROR_0001',
  GATEWAY_VALIDATOR_DTO_NOT_NULL_OR_UNDEFINED_ERROR_0001 = 'GATEWAY_VALIDATOR_DTO_NOT_NULL_OR_UNDEFINED_ERROR_0002',
  /**
   * Validator abstract status Errors
   */
  GATEWAY_VALIDATOR_DTO_ABSTRACT_STATUS_ERROR_0001 = 'GATEWAY_VALIDATOR_DTO_ABSTRACT_STATUS_ERROR_0001',
  GATEWAY_VALIDATOR_DTO_ABSTRACT_STATUS_ERROR_0002 = 'GATEWAY_VALIDATOR_DTO_ABSTRACT_STATUS_ERROR_0002',
  GATEWAY_VALIDATOR_DTO_ABSTRACT_STATUS_ERROR_0003 = 'GATEWAY_VALIDATOR_DTO_ABSTRACT_STATUS_ERROR_0003',

  /**
   * Validator Auth login Errors
   */
  GATEWAY_VALIDATOR_DTO_AUTH_LOGIN_ERROR_0001 = 'GATEWAY_VALIDATOR_DTO_AUTH_LOGIN_ERROR_0001',
  GATEWAY_VALIDATOR_DTO_AUTH_LOGIN_ERROR_0002 = 'GATEWAY_VALIDATOR_DTO_AUTH_LOGIN_ERROR_0002',
  GATEWAY_VALIDATOR_DTO_AUTH_LOGIN_ERROR_0003 = 'GATEWAY_VALIDATOR_DTO_AUTH_LOGIN_ERROR_0003',
  GATEWAY_VALIDATOR_DTO_AUTH_LOGIN_ERROR_0004 = 'GATEWAY_VALIDATOR_DTO_AUTH_LOGIN_ERROR_0004',

  /**
   * Validator Auth sigUp Errors
   */
  GATEWAY_VALIDATOR_DTO_AUTH_CONFIRM_SIG_UP_ERROR_0001 = 'GATEWAY_VALIDATOR_DTO_AUTH_CONFIRM_SIG_UP_ERROR_0001',
  GATEWAY_VALIDATOR_DTO_AUTH_CONFIRM_SIG_UP_ERROR_0002 = 'GATEWAY_VALIDATOR_DTO_AUTH_CONFIRM_SIG_UP_ERROR_0002',
  GATEWAY_VALIDATOR_DTO_AUTH_CONFIRM_SIG_UP_ERROR_0003 = 'GATEWAY_VALIDATOR_DTO_AUTH_CONFIRM_SIG_UP_ERROR_0003',
  GATEWAY_VALIDATOR_DTO_AUTH_CONFIRM_SIG_UP_ERROR_0004 = 'GATEWAY_VALIDATOR_DTO_AUTH_CONFIRM_SIG_UP_ERROR_0004',
  GATEWAY_VALIDATOR_DTO_AUTH_CONFIRM_SIG_UP_ERROR_0005 = 'GATEWAY_VALIDATOR_DTO_AUTH_CONFIRM_SIG_UP_ERROR_0005',
  GATEWAY_VALIDATOR_DTO_AUTH_CONFIRM_SIG_UP_ERROR_0006 = 'GATEWAY_VALIDATOR_DTO_AUTH_CONFIRM_SIG_UP_ERROR_0006',
  GATEWAY_VALIDATOR_DTO_AUTH_CONFIRM_SIG_UP_ERROR_0007 = 'GATEWAY_VALIDATOR_DTO_AUTH_CONFIRM_SIG_UP_ERROR_0007',

  /**
   * Validator Auth exchange code for token Errors
   */
  GATEWAY_VALIDATOR_DTO_AUTH_CONFIRM_EXCHANGE_CODE_TOKEN_ERROR_0001 = 'GATEWAY_VALIDATOR_DTO_AUTH_CONFIRM_EXCHANGE_CODE_TOKEN_ERROR_0001',
  GATEWAY_VALIDATOR_DTO_AUTH_CONFIRM_EXCHANGE_CODE_TOKEN_ERROR_0002 = 'GATEWAY_VALIDATOR_DTO_AUTH_CONFIRM_EXCHANGE_CODE_TOKEN_ERROR_0002',
  GATEWAY_VALIDATOR_DTO_AUTH_CONFIRM_EXCHANGE_CODE_TOKEN_ERROR_0003 = 'GATEWAY_VALIDATOR_DTO_AUTH_CONFIRM_EXCHANGE_CODE_TOKEN_ERROR_0003',
  GATEWAY_VALIDATOR_DTO_AUTH_CONFIRM_EXCHANGE_CODE_TOKEN_ERROR_0004 = 'GATEWAY_VALIDATOR_DTO_AUTH_CONFIRM_EXCHANGE_CODE_TOKEN_ERROR_0004',
  GATEWAY_VALIDATOR_DTO_AUTH_CONFIRM_EXCHANGE_CODE_TOKEN_ERROR_0005 = 'GATEWAY_VALIDATOR_DTO_AUTH_CONFIRM_EXCHANGE_CODE_TOKEN_ERROR_0005',
  GATEWAY_VALIDATOR_DTO_AUTH_CONFIRM_EXCHANGE_CODE_TOKEN_ERROR_0006 = 'GATEWAY_VALIDATOR_DTO_AUTH_CONFIRM_EXCHANGE_CODE_TOKEN_ERROR_0006',

  /**
   * Validator Auth logout Errors
   */
  GATEWAY_VALIDATOR_DTO_AUTH_LOGOUT_ERROR_0001 = 'GATEWAY_VALIDATOR_DTO_AUTH_LOGOUT_ERROR_0001',
  GATEWAY_VALIDATOR_DTO_AUTH_LOGOUT_ERROR_0002 = 'GATEWAY_VALIDATOR_DTO_AUTH_LOGOUT_ERROR_0002',
  GATEWAY_VALIDATOR_DTO_AUTH_LOGOUT_ERROR_0003 = 'GATEWAY_VALIDATOR_DTO_AUTH_LOGOUT_ERROR_0003',
  GATEWAY_VALIDATOR_DTO_AUTH_LOGOUT_ERROR_0004 = 'GATEWAY_VALIDATOR_DTO_AUTH_LOGOUT_ERROR_0004',

  /**
   * Validator Auth refresh token Errors
   */
  GATEWAY_VALIDATOR_DTO_AUTH_REFRESH_ERROR_0001 = 'GATEWAY_VALIDATOR_DTO_AUTH_REFRESH_ERROR_0001',

  /**
   * Validator Auth remove user Errors
   */
  GATEWAY_VALIDATOR_DTO_AUTH_REMOVE_USER_ERROR_0001 = 'GATEWAY_VALIDATOR_DTO_AUTH_REMOVE_USER_ERROR_0001',
  GATEWAY_VALIDATOR_DTO_AUTH_REMOVE_USER_ERROR_0002 = 'GATEWAY_VALIDATOR_DTO_AUTH_REMOVE_USER_ERROR_0002',

  /**
   * Validator Auth Resend Code Errors
   */
  GATEWAY_VALIDATOR_DTO_AUTH_RESEND_CODE_ERROR_0001 = 'GATEWAY_VALIDATOR_DTO_AUTH_RESEND_CODE_ERROR_0001',
  GATEWAY_VALIDATOR_DTO_AUTH_RESEND_CODE_ERROR_0002 = 'GATEWAY_VALIDATOR_DTO_AUTH_RESEND_CODE_ERROR_0002',

  /**
   * Validator Auth Confirm Account Recovery Errors
   */
  GATEWAY_VALIDATOR_DTO_AUTH_CONFIRM_ACCOUNT_RECOVERY_ERROR_0001 = 'GATEWAY_VALIDATOR_DTO_AUTH_CONFIRM_ACCOUNT_RECOVERY_ERROR_0001',
  GATEWAY_VALIDATOR_DTO_AUTH_CONFIRM_ACCOUNT_RECOVERY_ERROR_0002 = 'GATEWAY_VALIDATOR_DTO_AUTH_CONFIRM_ACCOUNT_RECOVERY_ERROR_0002',
  GATEWAY_VALIDATOR_DTO_AUTH_CONFIRM_ACCOUNT_RECOVERY_ERROR_0003 = 'GATEWAY_VALIDATOR_DTO_AUTH_CONFIRM_ACCOUNT_RECOVERY_ERROR_0003',
  GATEWAY_VALIDATOR_DTO_AUTH_CONFIRM_ACCOUNT_RECOVERY_ERROR_0004 = 'GATEWAY_VALIDATOR_DTO_AUTH_CONFIRM_ACCOUNT_RECOVERY_ERROR_0004',
  GATEWAY_VALIDATOR_DTO_AUTH_CONFIRM_ACCOUNT_RECOVERY_ERROR_0005 = 'GATEWAY_VALIDATOR_DTO_AUTH_CONFIRM_ACCOUNT_RECOVERY_ERROR_0005',
  GATEWAY_VALIDATOR_DTO_AUTH_CONFIRM_ACCOUNT_RECOVERY_ERROR_0006 = 'GATEWAY_VALIDATOR_DTO_AUTH_CONFIRM_ACCOUNT_RECOVERY_ERROR_006',

  /**
   * Validator Auth Initiate Account Recovery Errors
   */
  GATEWAY_VALIDATOR_DTO_AUTH_INITIATE_ACCOUNT_RECOVERY_ERROR_0001 = 'GATEWAY_VALIDATOR_DTO_AUTH_INITIATE_ACCOUNT_RECOVERY_ERROR_0001',
  GATEWAY_VALIDATOR_DTO_AUTH_INITIATE_ACCOUNT_RECOVERY_ERROR_0002 = 'GATEWAY_VALIDATOR_DTO_AUTH_INITIATE_ACCOUNT_RECOVERY_ERROR_0002',

  /**
   * Validator Role Created Errors
   */
  GATEWAY_VALIDATOR_DTO_ROLE_CREATED_ERROR_0001 = 'GATEWAY_VALIDATOR_DTO_ROLE_CREATED_ERROR_0001',
  GATEWAY_VALIDATOR_DTO_ROLE_CREATED_ERROR_0002 = 'GATEWAY_VALIDATOR_DTO_ROLE_CREATED_ERROR_0002',
  GATEWAY_VALIDATOR_DTO_ROLE_CREATED_ERROR_0003 = 'GATEWAY_VALIDATOR_DTO_ROLE_CREATED_ERROR_0003',
  GATEWAY_VALIDATOR_DTO_ROLE_CREATED_ERROR_0004 = 'GATEWAY_VALIDATOR_DTO_ROLE_CREATED_ERROR_0004',
  GATEWAY_VALIDATOR_DTO_ROLE_CREATED_ERROR_0005 = 'GATEWAY_VALIDATOR_DTO_ROLE_CREATED_ERROR_0005',
  GATEWAY_VALIDATOR_DTO_ROLE_CREATED_ERROR_0006 = 'GATEWAY_VALIDATOR_DTO_ROLE_CREATED_ERROR_0006',
  GATEWAY_VALIDATOR_DTO_ROLE_CREATED_ERROR_0007 = 'GATEWAY_VALIDATOR_DTO_ROLE_CREATED_ERROR_0007',
  GATEWAY_VALIDATOR_DTO_ROLE_CREATED_ERROR_0008 = 'GATEWAY_VALIDATOR_DTO_ROLE_CREATED_ERROR_0008',

  /**
   * Validator Role Find One Errors
   */
  GATEWAY_VALIDATOR_DTO_ROLE_FIND_ONE_ERROR_0001 = 'GATEWAY_VALIDATOR_DTO_ROLE_FIND_ONE_ERROR_0001',
  GATEWAY_VALIDATOR_DTO_ROLE_FIND_ONE_ERROR_0002 = 'GATEWAY_VALIDATOR_DTO_ROLE_FIND_ONE_ERROR_0002',
  GATEWAY_VALIDATOR_DTO_ROLE_FIND_ONE_ERROR_0003 = 'GATEWAY_VALIDATOR_DTO_ROLE_FIND_ONE_ERROR_0003',
  GATEWAY_VALIDATOR_DTO_ROLE_FIND_ONE_ERROR_0004 = 'GATEWAY_VALIDATOR_DTO_ROLE_FIND_ONE_ERROR_0004',

  /**
   * Validator Role Find Id Errors
   */
  GATEWAY_VALIDATOR_DTO_ROLE_FIND_ID_ERROR_0001 = 'GATEWAY_VALIDATOR_DTO_ROLE_FIND_ID_ERROR_0001',
  GATEWAY_VALIDATOR_DTO_ROLE_FIND_ID_ERROR_0002 = 'GATEWAY_VALIDATOR_DTO_ROLE_FIND_ID_ERROR_0002',
  GATEWAY_VALIDATOR_DTO_ROLE_FIND_ID_ERROR_0003 = 'GATEWAY_VALIDATOR_DTO_ROLE_FIND_ID_ERROR_0003',
  GATEWAY_VALIDATOR_DTO_ROLE_FIND_ID_ERROR_0004 = 'GATEWAY_VALIDATOR_DTO_ROLE_FIND_ID_ERROR_0004',

  /**
   * Validator Permission Created Errors
   */
  GATEWAY_VALIDATOR_DTO_PERMISSION_CREATED_ERROR_0001 = 'GATEWAY_VALIDATOR_DTO_PERMISSION_CREATED_ERROR_0001',
  GATEWAY_VALIDATOR_DTO_PERMISSION_CREATED_ERROR_0002 = 'GATEWAY_VALIDATOR_DTO_PERMISSION_CREATED_ERROR_0002',
  GATEWAY_VALIDATOR_DTO_PERMISSION_CREATED_ERROR_0003 = 'GATEWAY_VALIDATOR_DTO_PERMISSION_CREATED_ERROR_0003',
  GATEWAY_VALIDATOR_DTO_PERMISSION_CREATED_ERROR_0004 = 'GATEWAY_VALIDATOR_DTO_PERMISSION_CREATED_ERROR_0004',
  GATEWAY_VALIDATOR_DTO_PERMISSION_CREATED_ERROR_0005 = 'GATEWAY_VALIDATOR_DTO_PERMISSION_CREATED_ERROR_0005',
  GATEWAY_VALIDATOR_DTO_PERMISSION_CREATED_ERROR_0006 = 'GATEWAY_VALIDATOR_DTO_PERMISSION_CREATED_ERROR_0006',
  GATEWAY_VALIDATOR_DTO_PERMISSION_CREATED_ERROR_0007 = 'GATEWAY_VALIDATOR_DTO_PERMISSION_CREATED_ERROR_0007',
  GATEWAY_VALIDATOR_DTO_PERMISSION_CREATED_ERROR_0008 = 'GATEWAY_VALIDATOR_DTO_PERMISSION_CREATED_ERROR_0008',

  /**
   * Validator Permission Find One Errors
   */
  GATEWAY_VALIDATOR_DTO_PERMISSION_FIND_ONE_ERROR_0001 = 'GATEWAY_VALIDATOR_DTO_PERMISSION_FIND_ONE_ERROR_0001',
  GATEWAY_VALIDATOR_DTO_PERMISSION_FIND_ONE_ERROR_0002 = 'GATEWAY_VALIDATOR_DTO_PERMISSION_FIND_ONE_ERROR_0002',
  GATEWAY_VALIDATOR_DTO_PERMISSION_FIND_ONE_ERROR_0003 = 'GATEWAY_VALIDATOR_DTO_PERMISSION_FIND_ONE_ERROR_0003',
  GATEWAY_VALIDATOR_DTO_PERMISSION_FIND_ONE_ERROR_0004 = 'GATEWAY_VALIDATOR_DTO_PERMISSION_FIND_ONE_ERROR_0004',

  /**
   * Validator Permission Find Id Errors
   */
  GATEWAY_VALIDATOR_DTO_PERMISSION_FIND_ID_ERROR_0001 = 'GATEWAY_VALIDATOR_DTO_PERMISSION_FIND_ID_ERROR_0001',
  GATEWAY_VALIDATOR_DTO_PERMISSION_FIND_ID_ERROR_0002 = 'GATEWAY_VALIDATOR_DTO_PERMISSION_FIND_ID_ERROR_0002',
  GATEWAY_VALIDATOR_DTO_PERMISSION_FIND_ID_ERROR_0003 = 'GATEWAY_VALIDATOR_DTO_PERMISSION_FIND_ID_ERROR_0003',

  /**
   * Validator User Created Errors
   */
  GATEWAY_VALIDATOR_DTO_USER_CREATED_ERROR_0001 = 'GATEWAY_VALIDATOR_DTO_USER_CREATED_ERROR_0001',
  GATEWAY_VALIDATOR_DTO_USER_CREATED_ERROR_0002 = 'GATEWAY_VALIDATOR_DTO_USER_CREATED_ERROR_0002',
  GATEWAY_VALIDATOR_DTO_USER_CREATED_ERROR_0003 = 'GATEWAY_VALIDATOR_DTO_USER_CREATED_ERROR_0003',
  GATEWAY_VALIDATOR_DTO_USER_CREATED_ERROR_0004 = 'GATEWAY_VALIDATOR_DTO_USER_CREATED_ERROR_0004',
  GATEWAY_VALIDATOR_DTO_USER_CREATED_ERROR_0005 = 'GATEWAY_VALIDATOR_DTO_USER_CREATED_ERROR_0005',
  GATEWAY_VALIDATOR_DTO_USER_CREATED_ERROR_0006 = 'GATEWAY_VALIDATOR_DTO_USER_CREATED_ERROR_0006',
  GATEWAY_VALIDATOR_DTO_USER_CREATED_ERROR_0007 = 'GATEWAY_VALIDATOR_DTO_USER_CREATED_ERROR_0007',
  GATEWAY_VALIDATOR_DTO_USER_CREATED_ERROR_0008 = 'GATEWAY_VALIDATOR_DTO_USER_CREATED_ERROR_0008',
  GATEWAY_VALIDATOR_DTO_USER_CREATED_ERROR_0009 = 'GATEWAY_VALIDATOR_DTO_USER_CREATED_ERROR_0009',
  GATEWAY_VALIDATOR_DTO_USER_CREATED_ERROR_0010 = 'GATEWAY_VALIDATOR_DTO_USER_CREATED_ERROR_0010',
  GATEWAY_VALIDATOR_DTO_USER_CREATED_ERROR_0011 = 'GATEWAY_VALIDATOR_DTO_USER_CREATED_ERROR_0011',

  /**
   * Validator User Find One Errors
   */
  GATEWAY_VALIDATOR_DTO_USER_FIND_ONE_ERROR_0001 = 'GATEWAY_VALIDATOR_DTO_USER_FIND_ONE_ERROR_0001',
  GATEWAY_VALIDATOR_DTO_USER_FIND_ONE_ERROR_0002 = 'GATEWAY_VALIDATOR_DTO_USER_FIND_ONE_ERROR_0002',
  GATEWAY_VALIDATOR_DTO_USER_FIND_ONE_ERROR_0003 = 'GATEWAY_VALIDATOR_DTO_USER_FIND_ONE_ERROR_0003',
  GATEWAY_VALIDATOR_DTO_USER_FIND_ONE_ERROR_0004 = 'GATEWAY_VALIDATOR_DTO_USER_FIND_ONE_ERROR_0004',

  /**
   * Validator User Find Id Errors
   */
  GATEWAY_VALIDATOR_DTO_USER_FIND_ID_ERROR_0001 = 'GATEWAY_VALIDATOR_DTO_USER_FIND_ID_ERROR_0001',
  GATEWAY_VALIDATOR_DTO_USER_FIND_ID_ERROR_0002 = 'GATEWAY_VALIDATOR_DTO_USER_FIND_ID_ERROR_0002',
  GATEWAY_VALIDATOR_DTO_USER_FIND_ID_ERROR_0003 = 'GATEWAY_VALIDATOR_DTO_USER_FIND_ID_ERROR_0003',

  /**
   *
   *
   *
   *
   */

  /**
   * Access Control Mongodb Errors
   */
  MICRO_MANAGER_MONGO_DB_ERROR_0001 = 'MICRO_MANAGER_MONGO_DB_ERROR_0001', //'Invalid user credentials.',
  MICRO_MANAGER_MONGO_DB_ERROR_0002 = 'MICRO_MANAGER_MONGO_DB_ERROR_0002', //'Invalid user credentials.',
  MICRO_MANAGER_MONGO_DB_ERROR_0003 = 'MICRO_MANAGER_MONGO_DB_ERROR_0003', //'Invalid user credentials.',
  MICRO_MANAGER_MONGO_DB_ERROR_0004 = 'MICRO_MANAGER_MONGO_DB_ERROR_0004', //'Invalid user credentials.',
  MICRO_MANAGER_MONGO_DB_ERROR_0005 = 'MICRO_MANAGER_MONGO_DB_ERROR_0005', //'Invalid user credentials
  MICRO_MANAGER_MONGO_DB_ERROR_0006 = 'MICRO_MANAGER_MONGO_DB_ERROR_0006', //'Invalid user credentials.',
  MICRO_MANAGER_MONGO_DB_ERROR_0007 = 'MICRO_MANAGER_MONGO_DB_ERROR_0007', //'Invalid user credentials.',
  MICRO_MANAGER_MONGO_DB_ERROR_0008 = 'MICRO_MANAGER_MONGO_DB_ERROR_0008', //'Invalid user credentials.',
  MICRO_MANAGER_MONGO_DB_ERROR_0009 = 'MICRO_MANAGER_MONGO_DB_ERROR_0009', //'Invalid user credentials.',
  MICRO_MANAGER_MONGO_DB_ERROR_0010 = 'MICRO_MANAGER_MONGO_DB_ERROR_0010', //'Invalid user credentials.',
  MICRO_MANAGER_MONGO_DB_ERROR_0011 = 'MICRO_MANAGER_MONGO_DB_ERROR_0011', //'Invalid user credentials.',
  MICRO_MANAGER_MONGO_DB_ERROR_0012 = 'MICRO_MANAGER_MONGO_DB_ERROR_0012', //'Invalid user credentials.',

  /**
   * Cognito Errors
   */
  COGNITO_AUTH_ERROR_0000 = 'COGNITO_AUTH_ERROR_0000',
  COGNITO_AUTH_ERROR_0001 = 'COGNITO_AUTH_ERROR_0001',
  COGNITO_AUTH_ERROR_0002 = 'COGNITO_AUTH_ERROR_0002',
  COGNITO_AUTH_ERROR_0003 = 'COGNITO_AUTH_ERROR_0003',
  COGNITO_AUTH_ERROR_0004 = 'COGNITO_AUTH_ERROR_0004',
  COGNITO_AUTH_ERROR_0005 = 'COGNITO_AUTH_ERROR_0005',
  COGNITO_AUTH_ERROR_0006 = 'COGNITO_AUTH_ERROR_0006',
  COGNITO_AUTH_ERROR_0007 = 'COGNITO_AUTH_ERROR_0007',
  COGNITO_AUTH_ERROR_0008 = 'COGNITO_AUTH_ERROR_0008',
  COGNITO_AUTH_ERROR_0009 = 'COGNITO_AUTH_ERROR_0009',
  COGNITO_AUTH_ERROR_0010 = 'COGNITO_AUTH_ERROR_0010',
  COGNITO_AUTH_ERROR_0011 = 'COGNITO_AUTH_ERROR_0011',
  COGNITO_AUTH_ERROR_0012 = 'COGNITO_AUTH_ERROR_0012',
  COGNITO_AUTH_ERROR_0013 = 'COGNITO_AUTH_ERROR_0013',

  /**
   * User Errors
   */
  MICRO_MANAGER_USER_ERROR_0000 = 'MICRO_MANAGER_USER_ERROR_0000', //'Invalid request payload.',
  MICRO_MANAGER_USER_ERROR_0001 = 'MICRO_MANAGER_USER_ERROR_0001', //'Invalid request payload.',
  MICRO_MANAGER_USER_ERROR_0002 = 'MICRO_MANAGER_USER_ERROR_0002', //'Authentication failed.',
  MICRO_MANAGER_USER_ERROR_0003 = 'MICRO_MANAGER_USER_ERROR_0003', //'User does not exist.',
  MICRO_MANAGER_USER_ERROR_0004 = 'MICRO_MANAGER_USER_ERROR_0004', //'Invalid user credentials.',
  MICRO_MANAGER_USER_ERROR_0005 = 'MICRO_MANAGER_USER_ERROR_0005', //'Invalid user credentials.',
  MICRO_MANAGER_USER_ERROR_0006 = 'MICRO_MANAGER_USER_ERROR_0006', //'Invalid user credentials.',

  /**
   * Access Control Role Errors
   */
  MICRO_MANAGER_ACCESS_CONTROL_ERROR_0000 = 'MICRO_MANAGER_ACCESS_CONTROL_ERROR_0000', //'Invalid request payload.',
  MICRO_MANAGER_ACCESS_CONTROL_ROLE_ERROR_0001 = 'MICRO_MANAGER_ACCESS_CONTROL_ROLE_ERROR_0001', //'Invalid request payload.',
  MICRO_MANAGER_ACCESS_CONTROL_ROLE_ERROR_0002 = 'MICRO_MANAGER_ACCESS_CONTROL_ROLE_ERROR_0002', //'Authentication failed.',
  MICRO_MANAGER_ACCESS_CONTROL_ROLE_ERROR_0003 = 'MICRO_MANAGER_ACCESS_CONTROL_ROLE_ERROR_0003', //'User does not exist.',
  MICRO_MANAGER_ACCESS_CONTROL_ROLE_ERROR_0004 = 'MICRO_MANAGER_ACCESS_CONTROL_ROLE_ERROR_0004', //'Invalid user credentials.',
  MICRO_MANAGER_ACCESS_CONTROL_ROLE_ERROR_0005 = 'MICRO_MANAGER_ACCESS_CONTROL_ROLE_ERROR_0005', //'Invalid user credentials.',
  MICRO_MANAGER_ACCESS_CONTROL_ROLE_ERROR_0006 = 'MICRO_MANAGER_ACCESS_CONTROL_ROLE_ERROR_0006', //'Invalid user credentials.',

  /**
   * Access Control Permission Errors
   */
  MICRO_MANAGER_ACCESS_CONTROL_PERMISSION_ERROR_0007 = 'MICRO_MANAGER_ACCESS_CONTROL_PERMISSION_ERROR_0007', //'Invalid user credentials.',
  MICRO_MANAGER_ACCESS_CONTROL_PERMISSION_ERROR_0008 = 'MICRO_MANAGER_ACCESS_CONTROL_PERMISSION_ERROR_0008', //'Invalid user credentials.',
  MICRO_MANAGER_ACCESS_CONTROL_PERMISSION_ERROR_0009 = 'MICRO_MANAGER_ACCESS_CONTROL_PERMISSION_ERROR_0009', //'Invalid user credentials.',
  MICRO_MANAGER_ACCESS_CONTROL_PERMISSION_ERROR_0010 = 'MICRO_MANAGER_ACCESS_CONTROL_PERMISSION_ERROR_0010', //'Invalid user credentials.',
  MICRO_MANAGER_ACCESS_CONTROL_PERMISSION_ERROR_0011 = 'MICRO_MANAGER_ACCESS_CONTROL_PERMISSION_ERROR_0011', //'Invalid user credentials
  MICRO_MANAGER_ACCESS_CONTROL_PERMISSION_ERROR_0012 = 'MICRO_MANAGER_ACCESS_CONTROL_PERMISSION_ERROR_0012', //'Invalid user credentials.',
}
