export enum AuthResolverEnum {
  LOGIN_COGNITO = 'LOGIN_COGNITO',
  AUTH_COGNITO = 'AUTH_COGNITO',
  AUTH_REMOVE_COGNITO = 'AUTH_REMOVE_COGNITO',
  AUTH_VALIDATE_REGISTRATION = 'AUTH_VALIDATE_REGISTRATION',
  RESEND_CONFIMATION_CODE_COGNITO = 'RESEND_CONFIMATION_CODE_COGNITO',
}
