export enum OrganizationResolverEnum {
  ORGANIZATION_REGISTER = 'ORGANIZATION_REGISTER',
  ORGANIZATION_TOTAL = 'ORGANIZATION_TOTAL',
  ORGANIZATION_LIST = 'ORGANIZATION_LIST',
  ORGANIZATION_ID = 'ORGANIZATION_ID',
  ORGANIZATION_FIND_ONE = 'ORGANIZATION_FIND_ONE',
  ORGANIZATION_UPDATE = 'ORGANIZATION_UPDATE',
  ORGANIZATION_REMOVE = 'ORGANIZATION_REMOVE',
  ORGANIZATION_VALID = 'ORGANIZATION_VALID',
}
