export enum PermissionResolverEnum {
  PERMISSION_REGISTER = 'PERMISSION_REGISTER',
  PERMISSION_TOTAL = 'PERMISSION_TOTAL',
  PERMISSION_LIST = 'PERMISSION_LIST',
  PERMISSION_ID = 'PERMISSION_ID',
  PERMISSION_FIND_ONE = 'PERMISSION_FIND_ONE',
  PERMISSION_UPDATE = 'PERMISSION_UPDATE',
  PERMISSION_REMOVE = 'PERMISSION_REMOVE',
  PERMISSION_VALID = 'PERMISSION_VALID',
}
