export enum RoleResolverEnum {
  ROLE_REGISTER = 'ROLE_REGISTER',
  ROLE_TOTAL = 'ROLE_TOTAL',
  ROLE_LIST = 'ROLE_LIST',
  ROLE_ID = 'ROLE_ID',
  ROLE_FIND_ONE = 'ROLE_FIND_ONE',
  ROLE_UPDATE = 'ROLE_UPDATE',
  ROLE_REMOVE = 'ROLE_REMOVE',
  ROLE_VALID = 'ROLE_VALID',
}
