export enum UserResolverEnum {
  USER_REGISTER = 'USER_REGISTER',
  USER_TOTAL = 'USER_TOTAL',
  USER_LIST = 'USER_LIST',
  USER_ID = 'USER_ID',
  USER_FIND_ONE = 'USER_FIND_ONE',
  USER_UPDATE = 'USER_UPDATE',
  USER_REMOVE = 'USER_REMOVE',
  USER_VALID = 'USER_VALID',
}
